apiVersion: v1
kind: Service
metadata:
  name: my-react-app-service
spec:
  selector:
    app: my-react-app
  ports:
  - protocol: TCP
    port: 81
    targetPort: 80 # port wewnÄ…trz kontenera
  type: NodePort
